- name: "install node 12.X"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt -y upgrade
    sudo apt install -y nodejs
- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy files from CircleCI to server"
  become: true
  copy:
    src: /root/project/backend.tar
    dest: /home/ubuntu/backend/

- name: "untar & install package dependencies"
  become: true
  shell: |
    cd /home/ubuntu/backend/
    tar -xvf backend.tar
    cd backend
    npm install
